// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvjsaeprueaukcaixrgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2anNhZXBydWVhdWtjYWl4cmdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMTY5OTMsImV4cCI6MjA3MDg5Mjk5M30.NXxbbkdm6uMT64jqvNMdNedvR0POR3jUMt-4y9H3K1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});